version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: carbonchain-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: carbon
      POSTGRES_PASSWORD: carbonpass
      POSTGRES_DB: carbonchain
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}


